### ISSUE TITLE
UDP ports and related limitations

### ISSUE THREAD

**Issue by mc0e** [josegonzalez/dokku-ports#1]
Looking at the `commands` script, the commands sent to ufw are explicitly for TCP, regardless of whether the port is in fact UDP.

There's a bit more detail to the format of the ports arguments in docker commands.  You can put `EXPOSE 53/udp` in a Dockerfile, but you can't specify an external ip address to bind to.  If that functionality is wanted, this module would need to store some configuration independently of what's in the Dockerfile.

A scenario I'm looking at is running multiple postfix daemons, with things like specialised requirements like relaying to sendgrid accounts represented in different instances.  On the host I will have to choose port numbers for different postfix instances, but I'd rather not have to do that inside the containers.  Docker allows for mapping internal port numbers to different port numbers on the host, but this module's approach doesn't lend itself to that.

**Comment by heichblatt** [comment]
You are correct, this plugin assumes TCP ports. Patches welcome. :)
About binding to external ip addresses, that's simply out of scope for this plugin (and dokku iirc).
For your specific scenario you might want to look at fig.
